---
  - hosts: k8s-servers
    tasks:
     - name: copy kubernetes configuration file
       copy:
        src: /opt/k8s-files/spring-deployment.yml
        dest: /opt/k8s
     - name: create angular deployment
       shell: kubectl apply -f /opt/k8s/spring-deployment.yml	  